[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = "0.6.2"
hyper = "0.14.23"

[dev-dependencies]
reqwest = "0.11.13"
