redis_uri: "redis://127.0.0.1:6379"
application:
  port: 8000
  hmac_secret: "19478yugfk6784dyagrtdgf65fgjg56ytgfjgop8090inbcvfkudrt9888888888pu0348toghlio93-==93=00-"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
